WITH RESULT AS (
SELECT REQUESTER_ID AS ID FROM REQUESTACCEPTED
UNION ALL
SELECT ACCEPTER_ID AS ID FROM REQUESTACCEPTED)

SELECT ID, COUNT(ID) AS NUM
FROM RESULT
GROUP BY ID
ORDER BY NUM DESC
LIMIT 1;
