# Write your MySQL query statement below
WITH USER_RESULT AS (
SELECT USERS.NAME AS RESULTS, COUNT(MOVIERATING.MOVIE_ID) AS NUMBERS
FROM USERS
JOIN MOVIERATING
ON USERS.USER_ID = MOVIERATING.USER_ID
GROUP BY USERS.USER_ID
ORDER BY NUMBERS DESC, USERS.NAME ASC
LIMIT 1),
MOVIE_RESULT AS(
SELECT MOVIES.TITLE AS RESULTS, AVG(RATING) AS AVG_RATING
FROM MOVIES
JOIN MOVIERATING
ON MOVIES.MOVIE_ID = MOVIERATING.MOVIE_ID
WHERE DATE_FORMAT(CREATED_AT, '%Y-%m') = '2020-02'
GROUP BY MOVIES.MOVIE_ID
ORDER BY AVG_RATING DESC, MOVIES.TITLE ASC
LIMIT 1)

SELECT RESULTS
FROM USER_RESULT
UNION ALL
SELECT RESULTS
FROM MOVIE_RESULT

