# Write your MySQL query statement below
SELECT USERS.NAME, IFNULL(SUM(RIDES.DISTANCE), 0) AS TRAVELLED_DISTANCE
FROM USERS
LEFT JOIN RIDES
ON USERS.ID = RIDES.USER_ID
GROUP BY USERS.ID
ORDER BY TRAVELLED_DISTANCE DESC, USERS.NAME ASC;