# Write your MySQL query statement below
SELECT ACTIVITY_DATE AS DAY, COUNT(DISTINCT(USER_ID)) AS ACTIVE_USERS
FROM ACTIVITY 
GROUP BY ACTIVITY_DATE
HAVING DATEDIFF('2019-07-27', ACTIVITY_DATE) BETWEEN 0 AND 29
