# Write your MySQL query statement below
SELECT 'Low Salary' AS CATEGORY, COUNT(ACCOUNT_ID) AS ACCOUNTS_COUNT FROM ACCOUNTS WHERE INCOME < 20000
UNION
SELECT 'Average Salary' AS CATEGORY, COUNT(ACCOUNT_ID) AS ACCOUNT_COUNT  FROM ACCOUNTS WHERE INCOME BETWEEN 20000 AND 50000
UNION
SELECT 'High Salary' AS CATEGORY, COUNT(ACCOUNT_ID) AS ACCOUNT_COUNT FROM ACCOUNTS WHERE INCOME > 50000