# Write your MySQL query statement below
SELECT S.MACHINE_ID, ROUND(AVG(E.TIMESTAMP-S.TIMESTAMP), 3) AS PROCESSING_TIME
FROM ACTIVITY AS S
JOIN ACTIVITY AS E
ON S.MACHINE_ID = E.MACHINE_ID AND S.PROCESS_ID = E.PROCESS_ID
WHERE S.ACTIVITY_TYPE ='START' AND E.ACTIVITY_TYPE = 'END'
GROUP BY S.MACHINE_ID